### ISSUE TITLE
🐛 [BUG] - Some music have wrong lyrics

### ISSUE THREAD

**Issue by Miang141229** [boidushya/better-lyrics#100]
### Pre-checks

- [X] I confirm that I am following the pre-checks

### Description

Some music have wrong lyrics, hope can fix, thanks your extension, very beautiful.

![image](https://github.com/user-attachments/assets/f71f4f90-d07c-4796-8c15-20a699cfb620)
![image](https://github.com/user-attachments/assets/af35bf7c-a379-4a22-b2e8-53b773c21776)

[https://music.youtube.com/watch?v=3JuLZ78UPzY&si=ZytDuOhhHqcvVyH5](url)

### Reproduction steps

```bash

```

### Logs

```bash
Total lyrics in cache
2

Cache size
9.11 KB
```

### Browsers

Microsoft Edge

### Browser Version

131.0.2903.48

**Comment by boidushya** [comment]
Fixed!
