### ISSUE TITLE
🐛 [BUG] - Unable to save custom CSS on Firefox 133 due to lack of chrome.storage.sync.set(...) function

### ISSUE THREAD

**Issue by bmndc** [boidushya/better-lyrics#103]
### Pre-checks

- [X] I confirm that I am following the pre-checks

### Description

It's only custom CSS being affected—preset custom themes and other settings work okay. Chrome and other Chromium-based browsers are not affected. Refreshed YouTube Music, re-enabled the extension, tried refreshing and re-installing Firefox, doesn't seem to help.

### Reproduction steps

```bash
1. Open Better Lyrics extension menu;
2. Go to the Themes tab, and click on Create next to Custom CSS;
3. Notice that the status is stuck on Saving...; type some CSS code into the editor
4. Wait for a while and notice the status does not change. CSS code are not applied.

(error can only be seen under about:debugging)
```

### Logs

```bash
Uncaught TypeError: chrome.storage.sync.set(...) is undefined (editor.min.js:1:12483)
    e moz-extension://fcf6a4b7-e88a-40f4-8429-3cfbebfbeed5/src/options/editor.min.js:1
    setTimeout handler* moz-extension://fcf6a4b7-e88a-40f4-8429-3cfbebfbeed5/src/options/editor.min.js:1
    b moz-extension://fcf6a4b7-e88a-40f4-8429-3cfbebfbeed5/src/libs/codemirror/codemirror.min.js:1
    Zr moz-extension://fcf6a4b7-e88a-40f4-8429-3cfbebfbeed5/src/libs/codemirror/codemirror.min.js:1
    n moz-extension://fcf6a4b7-e88a-40f4-8429-3cfbebfbeed5/src/libs/codemirror/codemirror.min.js:1
    Il moz-extension://fcf6a4b7-e88a-40f4-8429-3cfbebfbeed5/src/libs/codemirror/codemirror.min.js:1
    <anonymous>	moz-extension://fcf6a4b7-e88a-40f4-8429-3cfbebfbeed5/src/options/editor.min.js:1
    Async* moz-extension://fcf6a4b7-e88a-40f4-8429-3cfbebfbeed5/src/options/editor.min.js:1
    EventListener.handleEvent* moz-extension://fcf6a4b7-e88a-40f4-8429-3cfbebfbeed5/src/options/editor.min.js:1
```

### Browsers

Firefox

### Browser Version

133.0

### Anything else?

Proposed fix: Firefox uses [`browser.storage.sync.set()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/set) instead of `chrome.storage.sync.set()`.

In this screenshot, I'm trying to change the font-family of the lyrics to use Roboto:

![{0FAD2B0E-6B6E-4AD7-8BCA-AD8FF0AD3382}](https://github.com/user-attachments/assets/1a896133-7381-45af-ad40-35c054c7ce48)

**Comment by boidushya** [comment]
Good catch!
Will fix soon :))

**Comment by boidushya** [comment]
should be fixed in #109 , feel free to reopen if something goes wrong

**Comment by boidushya** [comment]
you can try it out through this pre-release

https://github.com/boidushya/better-lyrics/releases/tag/v1.10.0-canary-4

**Comment by bmndc** [comment]
Nice, works great now, albeit I had to set !important on the `--blyrics-font-family` to get the font to change :')
