### ISSUE TITLE
Wrong lyrics

### ISSUE THREAD

**Issue by Tortillas-IT** [boidushya/better-lyrics#12]
Wrong lyrics for the song "Monster" from "Kanye West" (ye), idk how that is caused but on vanilla youtube music the lyrics is fine obviously

Edit: https://www.youtube.com/watch?v=b4I48PwEHeQ (video proof)

**Comment by boidushya** [comment]
Taking a look now

**Comment by Tortillas-IT** [comment]
> Taking a look now

Same issue with the song "Lost in The World" from "Kanye West" (ye)
![Schermata_20240611_195856](https://github.com/boidushya/better-lyrics/assets/69256413/2cca3040-03be-40ae-bdaa-734814dd55a3)

**Comment by boidushya** [comment]
I figured out the issue, its got to do with your localization.

Ill see what I can do about it, but changing your language to English should theoretically fix this

<img width="723" alt="image" src="https://github.com/boidushya/better-lyrics/assets/26746725/0d571e66-0a31-4780-a48f-1172e255e047">
<img width="666" alt="image" src="https://github.com/boidushya/better-lyrics/assets/26746725/d838c050-53e6-4540-9b77-ae9ea9cb62fd">

**Comment by Tortillas-IT** [comment]
> I figured out the issue, its got to do with your localization.
> 
> Ill see what I can do about it, but changing your language to English should theoretically fix this
> 
> <img alt="image" width="723" src="https://private-user-images.githubusercontent.com/26746725/338695844-0d571e66-0a31-4780-a48f-1172e255e047.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzAxNzUsIm5iZiI6MTcxODEyOTg3NSwicGF0aCI6Ii8yNjc0NjcyNS8zMzg2OTU4NDQtMGQ1NzFlNjYtMGEzMS00NzgwLWE0OGYtMTE3MmUyNTVlMDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE4MTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNGUwMDc3NTA3ZmFhOTM2MGI5YWRmNWE5ZTliY2Y4MWQ4NGZjZGRjM2Q3MGRjOWQ0NzAyY2JhZTNmMjRjNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7josGXQ_srKkx0R21HUT4Q2Tg1RVadHY-_ZTzhsNUY4"> <img alt="image" width="666" src="https://private-user-images.githubusercontent.com/26746725/338695964-d838c050-53e6-4540-9b77-ae9ea9cb62fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzAxNzUsIm5iZiI6MTcxODEyOTg3NSwicGF0aCI6Ii8yNjc0NjcyNS8zMzg2OTU5NjQtZDgzOGMwNTAtNTNlNi00NTQwLTliNzctYWU5ZWE5Y2I2MmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE4MTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZWI3YzhkMzg0NTU0OWIwNmI0NTQ4NDVlZDVjN2Q2MjhlYTc2ZGYxZGE2ZmU1MWJmMDllMWM4NjFiNjc1NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iI9cCN4_8mA1Ow5YI7zHtlij1xTpp4lap5v59ERVljE">

I'm italian, i think you can easily fix all localization issues by making detect from the exstension only the song name and not the featuring, too

**Comment by boidushya** [comment]
Fixed in [v1.4.0](https://github.com/boidushya/better-lyrics/releases/tag/v1.4.0)

It's going to take some time to get published so meanwhile you can test it out locally by following the instructions mentioned [here](https://github.com/boidushya/better-lyrics/tree/v1.4.0?tab=readme-ov-file#manual-installation)

If it doesn't work, feel free to tag me here and I'll reopen this issue

**Comment by Tortillas-IT** [comment]
> Fixed in [v1.4.0](https://github.com/boidushya/better-lyrics/releases/tag/v1.4.0)
> 
> It's going to take some time to get published so meanwhile you can test it out locally by following the instructions mentioned [here](https://github.com/boidushya/better-lyrics/tree/v1.4.0?tab=readme-ov-file#manual-installation)
> 
> If it doesn't work, feel free to tag me here and I'll reopen this issue

It's working fine, thanks
