### ISSUE TITLE
Not showing anymore the message if a song doesn't have lyrics

### ISSUE THREAD

**Issue by Tortillas-IT** [boidushya/better-lyrics#23]
After:
![Schermata_20240619_184848](https://github.com/boidushya/better-lyrics/assets/69256413/109be193-ee14-4c00-adaf-8e6a37e9a295)
Hi, i see you updated your exstension to not show for a bit the static lyrics before showing the live one. So this causes the message that a song doesn't have lyrics to not appear.

Before:
![Schermata_20240619_185115](https://github.com/boidushya/better-lyrics/assets/69256413/1cb1137c-adb6-494f-9992-b89e1820b0c2)
This should be an easy fix, great work about this fantastic exstension, thanks :D 

NOT RELATED: Btw i saw you on a thread about the project "Youtube Music Desktop App", thanks to give permission to other devs to use your code, this is what i love about open source community :) thanks

**Comment by boidushya** [comment]
Thats odd, are you on the latest version? v1.5.4? I tried it for the same song and i see the lyrics
<img width="1512" alt="image" src="https://github.com/boidushya/better-lyrics/assets/26746725/6c9fbe3e-9dc3-4dd7-a7f2-7287090e5683">

> NOT RELATED: Btw i saw you on a thread about the project "Youtube Music Desktop App", thanks to give permission to other devs to use your code, this is what i love about open source community :) thanks
Thank you!

**Comment by Tortillas-IT** [comment]
> Thats odd, are you on the latest version? v1.5.4? I tried it for the same song and i see the lyrics <img alt="image" width="1512" src="https://private-user-images.git
> 
> > NOT RELATED: Btw i saw you on a thread about the project "Youtube Music Desktop App", thanks to give permission to other devs to use your code, this is what i love about open source community :) thanks
> 
> Thank you!

That's "All of The Lights (Interlude)" not "All of The Lights"

**Comment by boidushya** [comment]
<img width="1512" alt="image" src="https://github.com/boidushya/better-lyrics/assets/26746725/af1a8138-de2a-4859-acba-f101a37c8245">
Ah here's the screenshot of All of the lights interlude on v1.5.5

**Comment by Tortillas-IT** [comment]
> Ah here's the screenshot of All of the lights interlude on v1.5.5

I don't see that message, it's just blank. Could it be a localization issue? (I have the latest version, 1.5.5)

**Comment by boidushya** [comment]
> Could it be a localization issue?

I doubt it, what do your logs say? Browser console i mean?

> Btw do you like the new playlist interface? I love it, feels so fresh

Dont think i got the update 😅

**Comment by Tortillas-IT** [comment]
> > Could it be a localization issue?
> 
> I doubt it, what do your logs say? Browser console i mean?
> 
> > Btw do you like the new playlist interface? I love it, feels so fresh
> 
> Dont think i got the update 😅

![Schermata_20240621_190552](https://github.com/boidushya/better-lyrics/assets/69256413/6f122a69-825d-44f7-b3ac-9d0062863c32)

**Comment by boidushya** [comment]
That's super odd, but i cant seem to repro it. I'll keep this issue open in case anyone else faces this

**Comment by boidushya** [comment]
Should be working properly in the latest release! v1.5.9
lmk if it doesn't 🤝

**Comment by Tortillas-IT** [comment]
Checked on 1.5.10 and still having the same issue

**Comment by boidushya** [comment]
> Checked on 1.5.10 and still having the same issue, please reopen this issue

Can you give me the repro steps? Its working for me with the song you provided.

**Comment by Tortillas-IT** [comment]
> > Checked on 1.5.10 and still having the same issue, please reopen this issue
> 
> Can you give me the repro steps? Its working for me with the song you provided.

As usually, play a song without lyrics and then go to lyrics tab, I tested with "All of the Lights (Interlude)"

**Comment by boidushya** [comment]
> > > Checked on 1.5.10 and still having the same issue, please reopen this issue
> > 
> > 
> > Can you give me the repro steps? Its working for me with the song you provided.
> 
> As usually, play a song without lyrics and then go to lyrics tab, I tested with "All of the Lights (Interlude)"

The issue is I've tried pretty much all possible ways and i always get the No Lyrics Found text. 

https://music.youtube.com/watch?v=v4QrSWRT5qI&list=OLAK5uy_lUlpor68rM1s9pkNM-8fNJRstJI5AsPWo

<img width="1440" alt="image" src="https://github.com/boidushya/better-lyrics/assets/26746725/b66ac678-cddc-490e-9f93-2903fca8b341">

I'm afraid I can't reopen this issue till I get some concrete steps to reciprocate this behaviour.

**Comment by Tortillas-IT** [comment]
> > > > Checked on 1.5.10 and still having the same issue, please reopen this issue
> > > 
> > > 
> > > Can you give me the repro steps? Its working for me with the song you provided.
> > 
> > 
> > As usually, play a song without lyrics and then go to lyrics tab, I tested with "All of the Lights (Interlude)"
> 
> The issue is I've tried pretty much all possible ways and i always get the No Lyrics Found text.
> 
> https://music.youtube.com/watch?v=v4QrSWRT5qI&list=OLAK5uy_lUlpor68rM1s9pkNM-8fNJRstJI5AsPWo
> 
> I'm afraid I can't reopen this issue till I get some concrete steps to reciprocate this behaviour.

I'm not at my PC rn, gonna check further later

**Comment by Tortillas-IT** [comment]
Console output:
![Schermata_20240626_180703](https://github.com/boidushya/better-lyrics/assets/69256413/2096d657-13a3-4990-812b-068a8a4a87a4)

Exstension settings:
![Schermata_20240626_180731](https://github.com/boidushya/better-lyrics/assets/69256413/7fe08156-3d2d-4bd3-bcb9-4e26f68af23a)

**Comment by boidushya** [comment]
Can you please drop the link to this song? there seems to be multiple versions of it (and all of them seem to work for me with the same settings...)

**Comment by Tortillas-IT** [comment]
> Can you please drop the link to this song? there seems to be multiple versions of it (and all of them seem to work for me with the same settings...)

https://music.youtube.com/watch?v=WHxRd_va950&si=vfw2XGxKHZK8StdA 

The one fron the album;-;

**Comment by boidushya** [comment]
Yea man this is incredibly odd, i just don't get this error, might have to do with youtube music having some kind of AB testing with their UI layout which messes with the selectors.

**Comment by Tortillas-IT** [comment]
I tried to reproduce the issue on my windows 11 partition and i'm getting the same issue there, too
