### ISSUE TITLE
Fetches wrong lyrics (sometimes) 

### ISSUE THREAD

**Issue by derptf2** [boidushya/better-lyrics#26]
it seems to sometimes mix up which lyrics to fetch if there's multiple songs with the same name or even a similar name, an example is "the name of heaven" (link: https://music.youtube.com/watch?v=f6cQZeBO1xk&si=irD0S2-5Zz0u17vA) it fetches the lyrics for "name of god" (link:https://music.youtube.com/watch?v=9bP-ed8YZ2U&si=U7wynL0GP2oWiIrZ)

**Comment by boidushya** [comment]
That's correct! This happens due to the current backend implementation. However it should be happening quite rarely. In any case, i do plan on having a db of sorts which would let users choose which lyrics are correct or at the very least "revert to yt lyrics" button in the roadmap
