### ISSUE TITLE
🐛 [BUG] - <Translation goes off screen when it's too long>

### ISSUE THREAD

**Issue by GitGitu79** [boidushya/better-lyrics#37]
### Pre-checks

- [X] I confirm that I am following the pre-checks

### Description

As you can see in screenshot 1 the translation is two line text, but when it's synced(screenshot 2) it become one line text and it goes off screen. Yes, even when the side panel is minimized it's still cut off(screenshot 3)

### Reproduction steps

```bash
1. Go to 'song'
2. Translate it
3. See long translation
4. Issue appear
```

### Logs

```bash
I don't know what it mean to copy and paste the log, it doesn't let me
```

### Browsers

Chrome

### Browser Version

127.0.6533.73

### Anything else?

![111111](https://github.com/user-attachments/assets/1bc8cd19-a80b-445e-950e-d392256b7d52)
![222222](https://github.com/user-attachments/assets/19072a3b-c7d5-4f9d-904c-0bdb436a44c0)
![33333](https://github.com/user-attachments/assets/d4f7325c-1c28-4332-8551-31a5f0e2559e)

**Comment by boidushya** [comment]
Hey thanks for bringing this up, which language are you translating to?
