### ISSUE TITLE
[Question] Lyrics unchanged

### ISSUE THREAD

**Issue by GitGitu79** [boidushya/better-lyrics#39]
Sometimes it just shows the youtube lyrics itself after "betterlyric trying to find lyrics". Is this a current limitation or a bug?

![unchanged](https://github.com/user-attachments/assets/18655065-4d75-4a6b-8864-b9dca4720e3d)

**Comment by boidushya** [comment]
This is a limitation since there are a few songs which don't have lyrics from the api I'm sourcing it from. Although this should happen in extremely rare cases.
