### ISSUE TITLE
🐛 [BUG] - Problem with formatting RTL text

### ISSUE THREAD

**Issue by mmahdium** [boidushya/better-lyrics#42]
### Pre-checks

- [X] I confirm that I am following the pre-checks

### Description

RTL Text isn't formatted properly. It is shown as an LTR text from end to beginning (If you want to read it from right to left).
Adding `dir="rtl"` in the class with id `blyrics-wrapper` resolves the issue.

Wrong formatting, have to read from left to right which is wrong:
![image](https://github.com/user-attachments/assets/3dc46b3f-ba1b-4bb9-98df-5b61a10b922c)

It shows correctly with `dir="rtl"`:
![image](https://github.com/user-attachments/assets/8641e38c-6ebc-4338-9b85-3b2af9856d2f)

### Reproduction steps

```bash
Go to any Persian-Arabic Song and click on lyrics:
e.g: https://music.youtube.com/watch?v=dsEeFL_yCCs&si=iKwShHq70V9rT3f6
```

### Logs

```bash
No LOG
```

### Browsers

Other Chromium Browsers (Brave, Opera, Vivaldi, Arc, etc.)

### Browser Version

124.0.6367.218

**Comment by boidushya** [comment]
Hey! Great suggestion! Adding it to my task list for the next release, will keep you updated
