### ISSUE TITLE
💡 [REQUEST] - <User can adjust the time stamp of the lyrics>

### ISSUE THREAD

**Issue by VinayChaurasiyaA** [boidushya/better-lyrics#47]
### Summary

As some of the songs are not sync properly so user can change the speed by clicking up or down by 1second

### Basic Example

As some of the songs are not sync properly so user can change the speed by clicking up or down by 1second

### Would you like to work on this feature?

- [X] I would like to work on this feature

**Comment by boidushya** [comment]
Duplicate of #35
