### ISSUE TITLE
💡 [REQUEST] - Optimization for full screen interface

### ISSUE THREAD

**Issue by dddanielliu** [boidushya/better-lyrics#48]
### Summary

In full screen mode with lyrics view, full size the album photo and fade a side seems a little bit unbalanced.
If show the full album art but smaller and place in the left and let lyrics takes more space, so that it will seems more comfortable to follow with the lyrics

### Basic Example

A current view is like this:
![Screenshot 2024-08-05 at 9 57 28 PM](https://github.com/user-attachments/assets/1fefb7e5-149f-42cb-88d7-e275cce13d55)

And after doing some search, I found out the apple music on apple tv fullscreen really fell more balanced in this case, I don't know if it is very hard to achieve, but just want to give some suggestions.
Here is a example pic of the Apple Music on Apple TV:
![Screenshot 2024-08-05 at 9 45 20 PM](https://github.com/user-attachments/assets/f4b6af30-192c-477a-aa30-296e92c9609d)

### Would you like to work on this feature?

- [ ] I would like to work on this feature

**Comment by boidushya** [comment]
I like this idea a lot! I'll get some work done to facilitate this..

**Comment by boidushya** [comment]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/771de635-9efb-4ab0-8c9f-970adb54dc67">

thoughts on something like this?

**Comment by dddanielliu** [comment]
wow oh my god its actually fantastic!! you are so fast hahaha.
is it able to let the width be something like 2:3 ratio 
just for example

![355155981-771de635-9efb-4ab0-8c9f-970adb54dc67](https://github.com/user-attachments/assets/47f92055-7c8b-4969-ba0e-237f60a0e8e8)

**Comment by boidushya** [comment]
I see! Yea that would look good, give me a sec

**Comment by dddanielliu** [comment]
Oh, by the way.
just thought of the situation when the user choose to show video instead of album art maybe when that case should be 1:1? 
Not so sure which is better based on different cases.

**Comment by boidushya** [comment]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/1aacd096-b6ed-407e-b20d-128eebff30a6">

This is what i have right now, thoughts?
Personally i still prefer the 50-50 division, even 2/3 makes it look a bit awkward

**Comment by boidushya** [comment]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/bf734389-8e79-427f-a959-9ddc6d449b08">
this is what it looks like without me cropping stuff

**Comment by boidushya** [comment]
you know what its actually growing on me

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/402f773e-311d-46f5-8869-67b5887b90f6">

**Comment by boidushya** [comment]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/f5c0de26-126e-48f8-be95-94da344a3ba6">
worked a lil bit more on it, this is what i got

**Comment by dddanielliu** [comment]
Sorry for being late.
I think I know what you talked about "awkward".
Is it because of the lack of **left**/(right) margin?

 I just drew a picture for example.
![IMG_709B989A7F4C-1](https://github.com/user-attachments/assets/d10793a8-4169-47d6-88ab-f8903b2e1e25)

**Comment by boidushya** [comment]
i think its all good now! it should be available under the latest version as well
also about the margins - thats gonna be hard to pull off since some songs have shorter lyrics per line and i cant really do anything about the whitespace. All in all it looks pretty decent now - let me know after you've tried it out

**Comment by dddanielliu** [comment]
Yeah I get it. Its already fantastic by the way!!!!

**Comment by dddanielliu** [comment]
Just notice a tiny bug of this, but it is kind of edge case thing.
when the user zoom in with ctrl + and after  multiple times the screen will be like this
![Screenshot 2024-08-06 at 6 43 16 AM](https://github.com/user-attachments/assets/9fe349dd-52db-492c-8276-35f3cf29c927)
![Screenshot 2024-08-06 at 6 43 29 AM](https://github.com/user-attachments/assets/4683dfab-6743-41f6-8dbd-784626ef6ab7)
![Screenshot 2024-08-06 at 6 43 38 AM](https://github.com/user-attachments/assets/73ba7bd5-820c-4751-8f1c-ea8b44232808)
![Screenshot 2024-08-06 at 6 43 44 AM](https://github.com/user-attachments/assets/d11d9992-5205-4e23-899b-e51e34aa6647)

or maybe that's another inspiring function of enlarging the lyrics without refreshing (screwing up the queue) 😆.

**Comment by boidushya** [comment]
thats for responsiveness, its actually done by youtube mostly. try changing the pages aspect ratio from inspect element (go into mobile mode) and you can see what it looks like on a mobile device. Zooming in basically just facilitates that

**Comment by dddanielliu** [comment]
I want to try but I can't find it...😅
