### ISSUE TITLE
🐛 [BUG] - Doesn't work well with non-music skip extensions and scripts

### ISSUE THREAD

**Issue by Razinal** [boidushya/better-lyrics#53]
### Pre-checks

- [X] I confirm that I am following the pre-checks

### Description

I use Firefox 129.0.1 and latest version of SponsorBlock add-on (v5.7). Both have auto update enabled.
I've tried replacing SponsorBlock with various scripts (only one of these scripts was active during each test) that serve the same function with Violentmonkey.
I've tried using only SponsorBlock or Violentmonkey with 'Better Lyrics' in private mode with a fresh profile.
Howevever regardless of either attempts  to solve this problem, As soon as a song with a non-music segment in it starts playing the lyrics of 'better lyrics' are no longer in sync with the song.
Most often it adhere to the original song's playback time and very rarely does it take into account the SponsorBlock's time changes and remain in sync with the auto-skips of non-music segments (regardless of whether using scripts or the official add-on).

### Reproduction steps

```bash
1. Install latest versions of SponsorBlock add-on and Firefox (Stable Channel).
2. Go to 'https://music.youtube.com' and sing-in.
3. Play any song with at least 1 non-music segment before the end of vocals.
4. Switch to Lyrics tab.
5. The song's lyrics will either start moving before any of vocals happen or the reverse will happen depending on where non-music segments are.
```

### Logs

```bash
The option 'show logs' does not actually send any message to developer console (Second tab from left when pressing F12 when a website is being displayed) on firefox even when all 8 categories that can be displayed are turned on (Blue colored font with a Blue line beneath them). Regardless of however many time I press CTRL+F5 and then play a song from beginning to the end and let the next song start playing, no mention of 'Better Lyrics' can be found either by going throught everything manually or using the 'Filter Output' function.
```

### Browsers

Firefox

### Browser Version

Windows 11 Pro Version 23H2 Build 22631 - Firefox 129.0.1 (64-bit) Stable Channel

**Comment by boidushya** [comment]
This mostly happens with Music Videos & non-official remixes!
More context here: https://github.com/boidushya/better-lyrics?tab=readme-ov-file#some-lyrics-are-out-of-syncmissingincorrect-what-can-i-do
