### ISSUE TITLE
🐛 [BUG] - Version 1.7 requires permission to access data on all websites (Firefox)

### ISSUE THREAD

**Issue by r3Fuze** [boidushya/better-lyrics#55]
### Pre-checks

- [X] I confirm that I am following the pre-checks

### Description

Version 1.7 requires a lot of new permissions that at first glance look **very** suspicious.

I can read from the code that clipboard, download, and tabs are related to the style import/export. It might be a good idea to add a FAQ entry explaining these permissions.

I can't see what the "all websites" permission is for though. It could be a bug, but if it's not it should also be documented.

### Reproduction steps

```bash
1. Wait for the auto update to request new permissions.
```

### Logs

```bash
N/A
```

### Browsers

Firefox

### Browser Version

130.0b5

### Anything else?

![image](https://github.com/user-attachments/assets/9b5e09c3-3417-4d67-8cc8-7b1749776e27)

**Comment by boidushya** [comment]
The first point is a firefox quirk iirc, its because the code editor's files need to be accessible whenever you open the extension, regardless of the site.

I'll add a detailed breakdown in README, thanks for bringing this up!

**Comment by boidushya** [comment]
Fixed - #56 
If any further explanation is required, feel free to bump

**Comment by Smart123s** [comment]
To be honest, I think this is a bit overkill. For example, the clipboard functionality can be achieved with `Ctrl` + `A`, `Ctrl` + `C` and `Ctrl` + `V`. There's no need to ask for that permission. Whilst I find your explanation in the readme convincing enough, with links to the code, for a non-developer the extension can seem sketch. The chrome webstore is full of extensions that replace crypto wallet addresses in your clipboard, etc. So I'm not sure that this copy button is worth that excessive permission request. That's just my personal opinion, it's absolutely up to you to handle the situation however you want to, I'm not here to argue, just wanted to give you another perspective.

As for the downloads, I've found [this](https://stackoverflow.com/a/19305829). I have absolutely zero idea if this still works, the answer is quite old, but it might be worth a shot. (Or Google might find this abusive, idk).

For "Access browser tabs", aren't [Host permissions](https://developer.chrome.com/docs/extensions/develop/concepts/declare-permissions#host-permissions) enough.
> Read and <i>query</i> the sensitive tab properties (url, title, and favIconUrl) using the chrome.tabs API.

I'm not a web extension developer, so I'm not sure if they work as I understood them from the docs, but it's be cool if you could take a look at these. And again, thanks for spending your time creating this awesome extension :)

**Comment by boidushya** [comment]
- Downloads : I tried it out before i added the downloads perms, it doesnt work
- Clipboard : You're right, it might be an overkill to add these two perms for it. Ill get it hashed it in an upcoming hotfix!
- Tabs : It is not unfortunately, you need to add the "tabs" perms to make sure you can access chrome.tabs

Thanks for the insight and thank you for being a user :))

**Comment by boidushya** [comment]
@Smart123s #57 should pretty much solve all issues
afraid firefox doesnt support optional perms so downloads is gonna be a requirement but apart from that everything else should be back to how it used to be!

**Comment by Smart123s** [comment]
Neat. Glad you took the time to research this! I think this will make people feel a lot safer installing this extension.
