### ISSUE TITLE
💡 [REQUEST] - Look into reducing the "Site access" scope down from being able to "read & change data on all websites"

### ISSUE THREAD

**Issue by BarnMTB** [boidushya/better-lyrics#60]
### Summary

Right now, the extension is requesting a permission to "read & change data on **all websites**" which can sound a bit scary to some users.

Since this extension only needs to work on YouTube Music (https://music.youtube.com/), it'd be a great idea to look into reducing/limiting the scope of websites that the extension has access to.

### Basic Example

Here's a prompt when installing from Edge store:
![image](https://github.com/user-attachments/assets/253148c3-980a-4104-a92a-8957478edfd0)

### Would you like to work on this feature?

- [ ] I would like to work on this feature

**Comment by boidushya** [comment]
Its required to inject code editor specific JS & CSS
