### ISSUE TITLE
💡 [REQUEST] - Support other lyrics sources

### ISSUE THREAD

**Issue by snowsharkt** [boidushya/better-lyrics#68]
### Summary

- Netease: From Chinese developers and users. Provides karaoke and synced lyrics.
- Musixmatch: A company from Italy. Provided synced lyrics.
I've used lyrics-plus and beautiful-lyrics from Spicetify before on Spotify and very like it. Maybe you can check their repo:
https://github.com/spicetify/cli/blob/main/CustomApps/lyrics-plus/README.md
https://github.com/surfbryce/beautiful-lyrics

### Basic Example

Image from lyrics-plus repo:
![image](https://github.com/user-attachments/assets/17299485-e384-4690-90fe-d875d06e509f)

### Would you like to work on this feature?

- [ ] I would like to work on this feature

**Comment by boidushya** [comment]
Thank you for the suggestion! This is already in our roadmap (#4 ) and we're planning on integrating it with netease and lrclib as fallback. We already source somewhat from musixmatch
