### ISSUE TITLE
💡 [REQUEST] - Lyric Romanisation Support

### ISSUE THREAD

**Issue by Immortaleye3115** [boidushya/better-lyrics#70]
### Summary

Love the extension and was wondering if support for romanised lyrics could be added, so that for example Russian and Japanese songs can be sung by English speakers.

### Basic Example

He's an example. The Japanese Lyric;
"気持ちがいいのよ すらすら歩いて いくのよ"

Would have it's romanised version;
"kimochi ga īnoyo surasura aruiteiku noyo"

Underneath it like how the English translation currently appears.

### Would you like to work on this feature?

- [ ] I would like to work on this feature

**Comment by boidushya** [comment]
Hey thanks for the issue, seems like so far @VinayChaurasiyaA has done a good job with it. Quick question, don't we also want to convert english to lets say Romanized Japanese?
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/60e97c94-0d03-422b-ba5d-759dabbb50c6">

Like for example here, if romanization is enabled, dont we also want to convert the japanese below to its romanized version?

**Comment by VinayChaurasiyaA** [comment]
> Hey thanks for the issue, seems like so far @VinayChaurasiyaA has done a good job with it. Quick question, don't we also want to convert english to lets say Romanized Japanese? <img alt="image" width="1552" src="https://private-user-images.githubusercontent.com/26746725/374485165-60e97c94-0d03-422b-ba5d-759dabbb50c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTY5ODAsIm5iZiI6MTcyODM5NjY4MCwicGF0aCI6Ii8yNjc0NjcyNS8zNzQ0ODUxNjUtNjBlOTdjOTQtMGQwMy00MjJiLWJhNWQtNzU5ZGFiYmI1MGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE0MTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZjZkOWEzOTZjMGE1NzQyMGYyODY3MmU1NzdmN2Q1ZmJhMjA4ZDcwNzIxMzA3Y2M3MmM2OGMzNDM5Njg2MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V65XnWDR2ZZHhL0SsJqw8MZwpEXYfP-S927AWGKqVw8">
> 
> Like for example here, if romanization is enabled, dont we also want to convert the japanese below to its romanized version?

I saw a few Romanizations and never saw it being the other way around, eg. if you are listening to a Japanese song it should help you sing in Japanese. otherwise, it will stuck in a loop of converting English to Japanese and Japanese to English... hence forth.

**Comment by boidushya** [comment]
Completed #77
