### ISSUE TITLE
💡 [REQUEST] - <Fallback to default Youtube Lyrics, or let user choose from a list of result>

### ISSUE THREAD

**Issue by ken-kuro** [boidushya/better-lyrics#98]
### Summary

The current lyric fetching mechanism, which relies on an API call, is not always reliable, especially when dealing with new songs or songs with similar titles and artists. Since the back-end implementation isn't public, I cannot verify it, but my guess is the API may not have the lyrics for new songs in its database yet, and it can be difficult to accurately identify the correct song when multiple songs share similar names and artists. To address this limitation, I propose implementing a fallback mechanism that will allow the extension to use default YouTube lyrics or provide a list of potential matches when the API fails to provide accurate results.

### Basic Example

An example would be these two songs: [Vinflow](https://music.youtube.com/watch?v=0PGbgpWlh9w) and [Trở về](https://music.youtube.com/watch?v=lV0OOyDUPII) by Wxrdie using the following two API calls:
```shell
curl 'https://lyrics-api.boidu.dev/getLyrics?s=Vinflow&a=Wxrdie%2C+WOKEUP%2C+%26+2pillz' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,vi;q=0.8' \
  -H 'origin: https://music.youtube.com' \
  -H 'priority: u=1, i' \
  -H 'referer: https://music.youtube.com/' \
  -H 'sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-arch: "x86"' \
  -H 'sec-ch-ua-bitness: "64"' \
  -H 'sec-ch-ua-form-factors: "Desktop"' \
  -H 'sec-ch-ua-full-version: "130.0.6723.116"' \
  -H 'sec-ch-ua-full-version-list: "Chromium";v="130.0.6723.116", "Google Chrome";v="130.0.6723.116", "Not?A_Brand";v="99.0.0.0"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-model: ""' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-ch-ua-platform-version: "6.11.7"' \
  -H 'sec-ch-ua-wow64: ?0' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'
  ```
and 
```shell
curl 'https://lyrics-api.boidu.dev/getLyrics?s=Wxrdie+-+TR%E1%BB%9E+V%E1%BB%80+%28ft.+JustaTee%29+%5Bprod.+by+Phongkhin%5D&a=Wxrdie' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,vi;q=0.8' \
  -H 'origin: https://music.youtube.com' \
  -H 'priority: u=1, i' \
  -H 'referer: https://music.youtube.com/' \
  -H 'sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-arch: "x86"' \
  -H 'sec-ch-ua-bitness: "64"' \
  -H 'sec-ch-ua-form-factors: "Desktop"' \
  -H 'sec-ch-ua-full-version: "130.0.6723.116"' \
  -H 'sec-ch-ua-full-version-list: "Chromium";v="130.0.6723.116", "Google Chrome";v="130.0.6723.116", "Not?A_Brand";v="99.0.0.0"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-model: ""' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-ch-ua-platform-version: "6.11.7"' \
  -H 'sec-ch-ua-wow64: ?0' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'
```
The response (at the time of reporting) for both API calls is the same with `trackId`: `6Ov6L8Iy0SMEl9w1TOUvaG`
![image](https://github.com/user-attachments/assets/723ff8da-bdcc-4150-ad4c-517a15c56edd)

### Would you like to work on this feature?

- [ ] I would like to work on this feature

**Comment by boidushya** [comment]
Hi! BetterLyrics v1.9.0+ already implements a fallback to lrclib.net in case a song isnt found from the official backend

**Comment by ken-kuro** [comment]
Thank you for the clarification. While the lrclib.net fallback is useful for cases where lyrics are completely unavailable, it doesn't address situations where the API returns incorrect lyrics for a song. As demonstrated in the example, the API can sometimes misidentify songs with similar titles and artists. To improve accuracy, consider implementing a fallback mechanism that prioritizes YouTube lyrics or provides a user-selectable list of potential matches.

**Comment by boidushya** [comment]
Unfortunately that goes against the ethos of Better Lyrics, we want to make things as streamlined as possible. While we may add a way to toggle sources later, its not something of immediate priority 

https://github.com/boidushya/better-lyrics?tab=readme-ov-file#can-i-use-a-different-lyrics-provider
